### ISSUE TITLE
How to handle MicroPC?

### ISSUE THREAD

**Issue by joshskidmore** [wimpysworld/umpc-ubuntu#14]
I've created an unofficial Ubuntu MATE ISO for the MicroPC using this script: https://gist.github.com/joshskidmore/fa799e12739709d656d55e3ea6e08175

I would love to provide you with a pull request, but I'm unsure of how you want to handle the 5.2 / mainline requirement to support Hans De Goede's upstream patches? Installing the packages would require a drop to chroot which really clutters the simplicity of your script.

Please let me know your thoughts on this, and I'll get you a pull request.

**Comment by flexiondotorg** [comment]
Tha ks for getting in touch 👍 I've got some changes locally that add some of the required changes to support the GPD MicroPC; I'll push them later.

That said, this doesn't include integrating the 5.2 mainline kernel. This is mainly due to the fact that while a 5.2 kernel can bring up the MicroPC display, the mainline kernels are lacking many features Ubuntu requires and introduce other ( on-hardware) compatibility issues. My current plan is to ship an Ubuntu MATE 19.10 image once the 5.2 kernel is available in 19.10.

**Comment by flexiondotorg** [comment]
Initial support added via https://github.com/wimpysworld/gpd-pocket2-ubuntu/commit/e46b045e91e4027627ecbc6e8085f8b38e521105

Linux 5.2 is in the proposed repository for Ubuntu 19.10 so should soon be available in the main archive and I can create an alpha image of Ubuntu MATE 19.10 that include MicroPC support.

**Comment by joshskidmore** [comment]
That's awesome! One minor mistake (which due to my script, is that the value in line `8` of [80-gpd-micropc-trackpoint.conf](https://github.com/wimpysworld/gpd-pocket2-ubuntu/blob/e46b045e91e4027627ecbc6e8085f8b38e521105/data/80-gpd-micropc-trackpoint.conf) should be `"2"`, not `"22"`. `"22"` works in the ISO that I've created, but I believe it's due to the fact that 22 becomes invalid and that the second button is the default scroll button.

**Comment by flexiondotorg** [comment]
Current status: https://twitter.com/m_wimpress/status/1150813877552254981
